# Generated by Django 5.2.8 on 2026-01-21 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='ai_audit',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='ai_reasoning',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='ai_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='ai_verified',
            field=models.BooleanField(default=False),
        ),
    ]
