# Generated by Django 5.2.8 on 2026-01-27 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_answer_image_question_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='ai_verified',
        ),
    ]
