# Generated by Django 5.2.8 on 2026-03-13 12:08

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_mentorsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True),
        ),
    ]
